### ISSUE TITLE
Object of class LibXMLError could not be converted to string

### ISSUE THREAD

**Issue by ghost** [wrklst/docxmustache#20]
in DocxMustache.php (line 350)

please help

**Comment by tobiasvielmetter** [comment]
Hi there, sorry for the delay. Please check head -> I just fixed the error reporter for xml errors.
Basically this means your file was not recognised as a workable xml file by php's xml interpreter. Therefor it cannot be parsed for img replacing. With the new error reporting added to head you should see where the problem is in your xml file.
