### ISSUE TITLE
Error on Document.xml

### ISSUE THREAD

**Issue by aramirez92** [wrklst/docxmustache#35]
Illuminate\Contracts\Filesystem\FileNotFoundException
DocxMustache/sample.docx5eafbd4f830f5/word/document.xml

**Comment by tobiasvielmetter** [comment]
@aramirez92 this is not a error report. If you whant to report something please do your debugging and explain what the actual issue is.

**Comment by agoalofalife** [comment]
@tobiasvielmetter I have same error for Laravel 7.12.0
I a little deep dig in code and saw that
https://github.com/wrklst/docxmustache/blob/master/src/WrkLst/DocxMustache/DocxMustache.php#L196

```php
        $this->word_doc = $this->ReadOpenXmlFile('word/document.xml', 'file');
```
that error happened when try to find `word/document.xml` in storage, what it that and for what?
I didn't see in an example
Is error `/DocxMustache/example_template.docx5ec7809e01839/word/document.xml`

**Comment by tobiasvielmetter** [comment]
@agoalofalife Hi there, this opens the main file of the document. According to the standards of a DOCX file the word/document.xml is there. You would have to debug what is actually there. Either the file has not properly unarchived to the new folder '/DocxMustache/example_template.docx5ec7809e01839/' or your DOCX file is broken and has not the proper 'word/document.xml' file. As stated above, if you have this issue, you need to debug it. Meaning you need to see why the error is reported and trace back what is actually there and what not and why there is a File not Found error. 
To assure you: I use this class in production and I do not have this issue. It is likely that the issue is with your setup, but if I get some actual information what is going wrong and it poses and issue with the class, I'd be happy to work on the class.
Thank you!

**Comment by agoalofalife** [comment]
@tobiasvielmetter in really I haven't that file in storage, maybe it depends on OS. I use MAC OS
Anyway, I didn't look for the cause of the error, I just use another package.

**Comment by tobiasvielmetter** [comment]
@agoalofalife ok, good luck
